#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
SDK=`$SCRIPT_DIR/get-sdk-install-folder`

REMOTE_WD="${PWD/#$HOME//home/mersdk/share}"
REMOTE_SCRIPT_DIR="${SCRIPT_DIR/#$HOME//home/mersdk/share}"

ssh \
  mersdk@127.0.0.1 \
  -p 2222 \
  -i "$SDK/vmshare/ssh/private_keys/engine/mersdk" \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  << EOF
set -e

cd "$REMOTE_WD"
$REMOTE_SCRIPT_DIR/build-targets-inner $@
EOF