#!/bin/bash -ex

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`

if [ $# -lt 2 ] ; then
	echo "Usage $0 ARCH CMD"
	exit 1
fi

ARCH="$1"
shift

VENV=`readlink -m "$SCRIPT_DIR/../.venv-$ARCH"`
TARGETS=(`sdk-assistant target list | grep $1`)

if [ ${#TARGETS[@]} -ne 1 ] ; then
  echo "No or more than one target found:" ${TARGETS[@]}
  exit 2
fi

sb2 -t ${TARGETS[0]} -m sdk-install -R $@