#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
ARCH=`gcc -dumpmachine | cut -d- -f1`
VENV=`readlink -m "$SCRIPT_DIR/../../.venv-$ARCH"`

# create virtualenv and install conan
if [ ! -d "$VENV" ] ; then
  echo "Install virtualenv ..."
  python3 -m pip install --no-warn-script-location --user --upgrade virtualenv

  echo "Create conan venv @ $VENV ..."
  ~/.local/bin/virtualenv --python=python3 "$VENV"
fi

if [ ! -f "$VENV/bin/conan" ] ; then
  echo "Install conan ..."
  source "$VENV/bin/activate"
  pip install conan conan_package_tools
fi

# speed up conan remote add
if ! grep -sq sailfishos "$HOME/.conan/registry.json" ; then
  conan remote add -f sailfishos https://api.bintray.com/conan/r1tschy/sailfishos
fi